### ISSUE TITLE
Blood moons can be skipped with a comforts sleeping bag

### ISSUE THREAD

**Issue by Ultrasquid9** [CorgiTaco/Enhanced-Celestials#13]
you can skip blood moons with the sleeping bag from comforts, despite not being able to sleep through the night with a bed.

**Comment by jellybean13** [comment]
Is this bug similar to the following one?
Description: If the player goes to bed before the value of daytime 13000, and the Blood Moon happens when the player is sleeping, the Blood Moon Event will be skipped.

One method to recurrent this bug:
First, use
`time set 12900`
Next go to sleep immediately.
And then, during the sleep, use
`/enhancedcelestials setlunarevent BLOOD_MOON`
Make sure this command executes successfully.
Finally, you can find that you skipped the Blood Moon event just now.

Suggestion: When the lunar event starts judging, and the judgment result is Blood Moon, before starting Blood Moon event, check whether someone is sleeping. If so, the Blood Moon Event won't happen. ([Optional] The probability of the Blood Moon event happens on the next night will be higher than the previous night.) If not, the Blood Moon event will happen normally.

**Comment by GeradesoLukas** [comment]
The same is true for campanion's sleeping bags

**Comment by viiizee** [comment]
The same's true for Druidcraft and Upgrade Aquatic.

**Comment by CorgiTaco** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3430183
