### ISSUE TITLE
[Bug]: I don't know how, but your mod breaks water physics. 

### ISSUE THREAD

**Issue by purejosh** [CorgiTaco/Enhanced-Celestials#132]
### Minecraft Version

1.18.2

### Enhanced Celestials Version

unimportant

### Mod Loader

Fabric

### Mod Loader Version

unimportant

### Bug Severity

Major

### What happened?

Newest release as of this github, and 1.19.2 fabric. I see you haven't updated your github template since 1.18.2, so that's indicative. 

Anyways. Installing this mod on my fabric server has entirely broken water physics. Gravity is as it should be on land, so you fall at air speed, not water speed. You cannot swim either. I don't know how you've done this, but yeah. 

I'll be uninstalling, since this mod appears to no longer be supported, judging by the amount of tickets that are open. just thought you should know. 

### latest.log

Not needed.

**Comment by CorgiTaco** [comment]
The mod is still supported, just have not gotten a chance to update the template(since tbh i really forgot) bc I've been busy with work. And I cannot recreate your issue, so it's probably either due to another mod or a combination of mods. And since no logs are provided I cannot help you much. I will close this issue. Feel free to make a new issue report with logs and provide a video as well.

**Comment by mintynoura** [comment]
You sound like a actual karen lmao

**Comment by purejosh** [comment]
> You sound like a actual karen lmao

How? Because I'm reporting an issue that's extremely bizarre? Please, unless you're doing something worthwhile, piss off.
