### ISSUE TITLE
[Bug]: Celestial Moon Retains Texture of Last Lunar Event

### ISSUE THREAD

**Issue by lithospace** [CorgiTaco/Enhanced-Celestials#143]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

v2.1.0.2

### Mod Loader

Fabric

### Mod Loader Version

0.14.10

### Bug Severity

Minor

### What happened?

Ok so the moon will keep its texture from the previous lunar event and will not change to it's default texture afterwards. If a harvest moon happens then it will stay a harvest moon texture until the next lunar event and not reset to its normal texture. 
The latest.log below is from the server. I am running this mod on a multiplayer server.

### latest.log

<script src="https://gist.github.com/InfidelKilla/bfb7f97531bf2fd45b26d9cb1adee007.js"></script>

**Comment by PoipleToitle** [comment]
I'm having the same issue...

**Comment by Alkiasan** [comment]
Same issue here, too.

**Comment by JensGL05** [comment]
I have this problem on the Forge version as well.

**Comment by aquaticp7886** [comment]
Having this issue here too, running 1.19.2 on Fabric with my hardcore world. It's pretty annoying when I come up from my mines.

**Comment by ildiem** [comment]
Same issue as well here, Forge 1.19.2 on EC 2.1.0.2

**Comment by CorgiTaco** [comment]
Should be fixed in the latest version,

Get it here: 
Forge: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/4392661 / https://modrinth.com/mod/enhanced-celestials/version/1.19.2-2.1.0.4-forge
Fabric: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric/files/4392659 / https://modrinth.com/mod/enhanced-celestials/version/1.19.2-2.1.0.4-fabric
