### ISSUE TITLE
[Bug]: Possible Incompatibility with Alloy Forgery

### ISSUE THREAD

**Issue by Ultimushadow** [CorgiTaco/Enhanced-Celestials#174]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

1.20.1-5.0.0.2

### Mod Loader

Fabric

### Mod Loader Version

14.21/14.22

### Bug Severity

Major

### What happened?

Bug report does not allow me to select the correct MC version, but this crash occurs with the latest release on 1.20.1
Attempting to load both gives the attached crash, both work just fine without the other loaded.
Mod versions:
 - CorgiLib 4.0.0.4
 - Enhanced Celestials 5.0.0.2
 - owo 0.11.1
 - Alloy Forgery 2.0.22

### latest.log

Crash: [crash-2023-08-23_05.03.37-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/12417952/crash-2023-08-23_05.03.37-server.txt)

Log: [latest.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/12417924/latest.log)

**Comment by Linguardium** [comment]
issue is due to load timing with fabric api's dynamic registries. Mod was last updated before they existed and adds stuff to the vanilla registries during mod init, which can break if some other mod loads the registry class first. easy fix is for the dev to migrate to fabric api's dynamic registry system

**Comment by CorgiTaco** [comment]
Fixed for versions 5.0.0.3 and beyond!
