### ISSUE TITLE
Ignoring datapack

### ISSUE THREAD

**Issue by Aceplante** [CorgiTaco/Enhanced-Celestials#192]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

1.20.1

### Mod Loader

Forge

### Mod Loader Version

latest

### Bug Severity

Minor

### What happened?

I do not want the player to be signaled by a chat message. I assumed the way to do this was to remove the text components part, leaving:

"text_components": {}

however, it did not work, and seems to completely ignore the datapack files

### latest.log

n/a

**Comment by FernandoCalaza** [comment]
Perhaps the contents of the text components are mandatory, but the contents of the start and end text messages are optional. Try to maintain the structure of the text component, but leave the message fields empty.

More info: https://github.com/CorgiTaco/Enhanced-Celestials/wiki/Lunar-Text-Components

When a datapack is ignored it is because it was not read correctly. In your case, I think it's because it's outside the standard of the original code.

**Comment by Aceplante** [comment]
then the event did not seem to happen

**Comment by CorgiTaco** [comment]
Due to the lack of time I will no longer be supporting versions of this mod that are 1.20 and lower. Apologies for the inconvenience.

**Comment by DraconicArcher** [comment]
Sorry, man. Corgi asked me to look into this for you, but it was my birthday, then the holidays, and you know how it is.

So, if you change the notification type to NONE instead of CHAT, then the start and end of a moon will have a blank notification pop up in chat instead of a message. Don't know why it still does that, but that's the best solution I've found.

Hit me up in either Corgi's discord or mine for further support. I'll be happy to help in real time!
